name: blueframe
description: A higher level web framework built on top of Aqueduct.
version: 0.0.1
author: Blue[] <alexander.i.walker@outlook.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  mysql1: ^0.17.0+1
  sqljocky5: ^2.2.1


dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0